var paths = [
  "TEI.2 teiHeader encodingDesc refsDecl",
  "TEI.2 text body div1",
  "TEI.2 text body div1 l",
  "TEI.2 teiHeader fileDesc",
  "TEI.2 text body div1 div2 p",
  "TEI.2 text body div1 div2 p seg q",
  "TEI.2 text body div1 div2 p quote",
  "TEI.2 text body",
  "TEI.2 text body div1 div2 div3",
  "TEI.2 text body div1 div2 div3 p",
  "TEI.2 text body div1 div2",
  "TEI.2 text body div1 sp",
  "TEI.2 text body div1 sp l",
  "TEI.2 text body div1 div2 sp l",
  "TEI.2 text body div1 div2 sp",
  "TEI.2 text body div1 sp l add",
  "TEI.2 text body div1 div2 sp l add",
  "TEI.2 text body div1 sp p",
  "TEI.2 text front div1",
  "TEI teiHeader encodingDesc refsDecl",
  "TEI teiHeader revisionDesc change",
  "TEI.2 teiHeader fileDesc sourceDesc biblStruct",
  "TEI.2 teiHeader fileDesc sourceDesc listBibl biblStruct",
  "TEI.2 teiHeader revisionDesc change respStmt",
  "TEI.2 text body div1 div2 p note foreign",
  "TEI.2 text body div1 div2 p note",
  "TEI.2 text body div1 div2 p cit quote l note foreign",
  "TEI.2 text body div1 div2 p quote l note foreign",
  "TEI.2 text body div1 p",
  "TEI.2 text body div1 p q",
  "TEI.2 text body div1 div2 p note gloss",
  "TEI.2 text body div1 div2 p quote l",
  "TEI text body div div p",
  "TEI.2 text body div1 head",
  "TEI.2 teiHeader revisionDesc change",
  "TEI.2 text body div1 p quote l",
  "TEI.2 text body div1 p quote",
  "TEI.2 text body head",
  "TEI.2 text body div1 div2 p q",
  "TEI.2 text body div1 p text body p",
  "TEI.2 text body div1 head note",
  "TEI.2 text body div1 p note",
  "TEI.2 text body div1 div2 p q p",
  "TEI.2 text body div1 p q q",
  "TEI.2 text body div1 p hi",
  "TEI.2 text body div1 div2 head",
  "TEI.2 text body div1 div2 div3 p q",
  "TEI.2 text body div1 div2 div3 p quote l",
  "TEI.2 text body div1 div2 div3 p quote",
  "TEI.2 text",
  "TEI text body",
  "TEI text body div",
  "TEI text body div div p quote",
  "TEI text body div div",
  "TEI text body div div quote",
  "TEI text body div div p quote l",
  "TEI.2 text body div1 p quote q quote",
  "TEI.2 text body div1 p quote quote",
  "TEI.2 text body div1 p quote q",
  "TEI.2 text body div1 p quote sp l",
  "TEI.2 text body div1 p q quote",
  "TEI.2 text body div1 p q q q",
  "TEI.2 text body div1 p q q quote",
  "TEI.2 text body div1 p quote p",
  "TEI.2 text body div1 p quote p q",
  "TEI.2 text body div1 p quote p quote",
  "TEI.2 text body div1 p q p",
  "TEI.2 text body div1 p quote p quote p",
  "TEI.2 text body div1 p quote p quote p quote",
  "TEI.2 text body div1 p quote p quote p q",
  "TEI.2 text body div1 p quote p quote q",
  "TEI.2 text body div1 p quote p quote quote",
  "TEI.2 text body div1 p quote q q",
  "TEI.2 text body div1 p quote quote quote",
  "TEI.2 text body div1 p quote p q q",
  "TEI.2 text body div1 p q quote quote",
  "TEI.2 text body div1 p q quote q",
  "TEI.2 text body div1 p quote p q p",
  "TEI.2 text body div1 p quote p q p quote",
  "TEI.2 text body div1 p quote p q q quote",
  "TEI.2 text body div1 p quote p q quote",
  "TEI.2 text body div1 p quote quote q",
  "TEI.2 text body div1 p quote quote q q",
  "TEI.2 text body div1 p q p q",
  "TEI.2 text body div1 p q p quote",
  "TEI.2 text body div1 p label",
  "TEI teiHeader fileDesc",
  "TEI text body div div p cit quote l",
  "TEI text body div div p cit",
  "TEI text body div div p bibl",
  "TEI.2 text body sp l",
  "TEI.2 text body div1 div2 p quote quote",
  "TEI.2 text body div1 q",
  "TEI.2 text body div1 q l",
  "TEI.2 text body div1 q q",
  "TEI.2 text body div1 q q l",
  "TEI.2 text body div1 q q q",
  "TEI.2 text body div1 q q q l",
  "TEI.2 text body div1 q q q q",
  "TEI.2 text body div1 q q q q l",
  "TEI.2 text body div1 q q q q q l",
  "TEI.2 text body div1 q q q q q",
  "TEI.2 text body div1 q q q q q q",
  "TEI.2 text body div1 q q q q q q l",
  "TEI text body div p",
  "TEI.2 teiHeader profileDesc",
  "TEI.2 teiHeader fileDesc notesStmt",
  "TEI.2 text body div",
  "TEI.2 text body div1 div2 p hi",
  "TEI text body div said",
  "TEI text body div said quote",
  "TEI.2 text body div1 sp p note",
  "TEI.2 text body div1 sp p q",
  "TEI.2 text body div1 p add",
  "TEI text body div said note",
  "TEI.2 text body div1 sp p quote l q",
  "TEI.2 text body div1 sp p quote l",
  "TEI.2 text body div1 div2 div3 p del",
  "TEI.2 text body div1 argument p",
  "TEI.2 text body div1 sp p q quote l",
  "TEI.2 text body div1 sp p quote",
  "TEI.2 text body div1 sp p q q",
  "TEI.2 text body p",
  "TEI.2 text group text body",
  "TEI.2 text group text body div1 sp p",
  "TEI.2 text group text body div1",
  "TEI.2 text group text body div1 p",
  "TEI.2 text body div1 div2 sp p",
  "TEI.2 text body div1 div2 sp p q",
  "TEI text body div div sp p",
  "TEI text body div div sp",
  "TEI.2 text group text body sp p",
  "TEI.2 text body div1 p quote add",
  "TEI.2 text body div1 div2 div3 div4 p add",
  "TEI.2 text body div1 div2 p quote lg l",
  "TEI.2 text body div1 p cit quote",
  "TEI.2 text body div1 p table row cell",
  "TEI.2 text body div1 p del",
  "TEI.2 text body div1 p quote lg l",
  "TEI.2 text body div1 p cit quote l",
  "TEI.2 text body div1 div2 div3 p note foreign",
  "TEI.2 teiHeader fileDesc sourceDesc listBibl biblStruct monogr",
  "TEI.2 text body div1 div2 div3 div4 p",
  "TEI.2 text body div1 div2 div3 div4 p quote",
  "TEI.2 text body div1 div2 div3 p note",
  "TEI.2 text body div1 argument p note",
  "TEI.2 text body div1 note list",
  "TEI.2 text body div1 note list item",
  "TEI.2 text body div1 div2 p del",
  "TEI.2 text body div1 div2 p foreign",
  "TEI.2 text body div1 div2 div3 p quote p",
  "TEI.2 text body div1 p cit q p",
  "TEI.2 text body div1 p cit q p q",
  "TEI.2 text body div1 div2 p note p table row",
  "TEI.2 text body div1 div2 p note p figure figDesc rs",
  "TEI.2 text body div div div p",
  "TEI.2 text body div div div p cit quote l",
  "TEI.2 text body div div p",
  "TEI.2 text body div div p cit quote",
  "TEI.2 text body div div p quote l",
  "TEI.2 text body div p",
  "TEI.2 text body div1 div2 p quote del",
  "TEI.2 text body div1 div2 p cit quote",
  "TEI.2 text body div1 div2 p add",
  "TEI.2 text body div1 div2 p q quote",
  "TEI.2 text body div1 div2 p q q",
  "TEI.2 text body sp p",
  "TEI.2 text body sp p q",
  "TEI.2 text body sp p quote",
  "TEI text body div div p q",
  "TEI.2 text front",
  "TEI.2 text front div1 p",
  "TEI.2 text front div1 p quote",
  "TEI.2 text front div1 p note",
  "TEI.2 text front div1 p foreign",
  "TEI.2 text front div1 p quote p",
  "TEI.2 text front div1 div2",
  "TEI.2 text front div1 div2 p emph",
  "TEI.2 text front div1 div2 p quote",
  "TEI.2 text front div1 div2 p",
  "TEI.2 text front div1 div2 div3 p quote",
  "TEI.2 text front div1 div2 div3 p",
  "TEI.2 text body div1 div2 div3 note p",
  "TEI.2 text body div1 div2 div3 div4 p hi",
  "TEI.2 text body div1 div2 div3 note p quote",
  "TEI.2 text body div1 div2 div3 note",
  "TEI.2 text body div1 div2 div3 p hi",
  "TEI.2 text body div1 div2 div3 p emph",
  "TEI.2 text body div1 div2 div3 div4",
  "TEI.2 text back",
  "TEI.2 text body p q",
  "TEI.2 text body p q p",
  "TEI.2 text body div1 p note lemma",
  "TEI.2 text body div1 div2 l",
  "TEI.2 text body div1 div2 l add",
  "TEI.2 text body div1 div2 note",
  "TEI.2 text body div1 div2 cit quote sp",
  "TEI.2 text body div1 cit quote l",
  "TEI.2 text body div1 cit quote",
  "TEI.2 text body div1 div2 sp l del",
  "TEI.2 text body div1 div2 sp l foreign",
  "TEI.2 text body div1 sp speaker",
  "TEI.2 text body div1 div2 cit quote",
  "TEI.2 text body div1 div2 cit quote sp l",
  "TEI.2 text body div1 div2 cit quote l",
  "TEI.2 text body div1 div2 sp lg",
  "TEI.2 text body div1 div2 sp lg l",
  "TEI.2 teiHeader fileDesc sourceDesc biblStruct monogr",
  "TEI.2 text body div1 lg l",
  "TEI.2 teiHeader fileDesc sourceDesc",
  "TEI.2 text body div1 div2 lg l",
  "TEI.2 text body div1 p note quote l",
  "TEI.2 teiHeader fileDesc sourceDesc biblStruct monogr imprint",
  "TEI.2 text back div1",
  "TEI.2 text body div1 div2 p cit",
  "TEI.2 text body div1 div2 p cit quote p",
  "TEI.2 text body div1 div2 cit quote p",
  "TEI.2 text front div1 table row",
  "TEI.2 text front div1 table",
  "TEI.2 text body div1 quote",
  "TEI.2 text back div1 table row",
  "TEI.2 text back div1 p",
  "TEI.2 teiHeader revisionDesc change item",
  "TEI.2 text front div1 p table row cell hi",
  "TEI.2 text body div1 div2 p quote l note",
  "TEI.2 text body div1 div2 p note hi",
  "TEI.2 text body div1 p note hi",
  "TEI.2 text body div1 p note p",
  "TEI.2 text body div1 div2 p quote note",
  "TEI.2 text body div1 div2 l note",
  "TEI.2 text body div1 div2 p quote note note",
  "TEI.2 text body div1 div2 p quote quote l note",
  "TEI.2 text body div1 div2 p quote sp l",
  "TEI.2 text body div1 div2 p quote quote l",
  "TEI.2 text body div1 div2 p quote sp",
  "TEI.2 text body div1 div2 div3 p date",
  "TEI.2 text body div1 div2 div3 p foreign",
  "TEI.2 text body div1 div2 div3 p quote text body p",
  "TEI.2 text body div1 p note quote",
  "TEI.2 teiHeader fileDesc titleStmt",
  "TEI.2 text body div1 div2 div3 p add",
  "TEI.2 text body div1 div2 div3 p note p cit",
  "TEI.2 text body div1 div2 p note p cit",
  "TEI.2 text body div1 p note p cit",
  "TEI.2 text body l",
  "TEI.2 text body p hi",
  "TEI.2 text body div1 note q",
  "TEI.2 text body div1 div2 p note p",
  "TEI.2 text body div1 div2 p note table row",
  "TEI.2 text body div0 div1",
  "TEI.2 text body div0 div1 p",
  "TEI.2 text body div0 div1 p foreign",
  "TEI.2 text body div0 div1 p hi",
  "TEI.2 text body div0 div1 p persName",
  "TEI.2 text body div0",
  "TEI.2 text body div1 div2 div3 p cit quote",
  "TEI.2 text body div1 div2 div3 p cit quote add",
  "TEI.2 text body div1 div2 div3 p quote cit quote",
  "TEI.2 text body sp",
  "TEI.2 text body div1 note",
  "TEI.2 text body div1 l del",
  "TEI.2 text body div1 l note",
  "TEI.2 text body div1 l note hi",
  "TEI.2 text body div1 p foreign",
  "TEI.2 text body div1 p quote foreign",
  "TEI.2 text body div1 div2 div3 div4 p q",
  "TEI.2 text body div1 div2 div3 div4 p note",
  "TEI.2 text body div1 div2 argument p",
  "TEI.2 text body div1 div2 quote",
  "TEI.2 text body div1 div2 div3 quote l",
  "TEI.2 text body div1 div2 div3 quote l note",
  "TEI.2 text body div1 div2 argument p note",
  "TEI.2 text body div1 div2 opener salute",
  "TEI.2 text body div div div",
  "TEI.2 text body div div div p note hi",
  "TEI.2 text body div div div p note",
  "TEI.2 text body div div",
  "TEI.2 text body div div l",
  "TEI.2 text body div lg",
  "TEI.2 text body div l",
  "TEI.2 text body div p quote",
  "TEI.2 text body div div p quote",
  "TEI.2 text body div head",
  "TEI.2 text body div1 div2 p q q q"
]
